56 create textquestionanalytics component
hack4impact-utk/internal-applications pull request #157
Opened 2024-04-03 21:41 UTC by jmcheek

# Description
A TextQuestionAnalytics component was created to display a list of question answers (submissions) by different users to a single form.  

This code was used to test the component on page.tsx:

```
import TextQuestionAnalytics from '@/components/FormSubmissions/TextQuestionAnalytics';
import { getFormById } from '@/server/actions/forms';

export default async function Home() {
  const form = await `getFormById('656ea21e70fac31f8c4aab56');`
  return (
    <div>
      <h1>Home page</h1>
      <TextQuestionAnalytics
        question={form!.questions[0]}
        responses={form!.submissions}
      />
    </div>
  );
}
```

## Relevant issue(s)

- #56 
 

## Questions
 None 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

2024-04-09 03:52 UTC, LSmith2174 requested changes
Needs a few changes but great job! :) 👍

2024-04-09 03:52 UTC, LSmith2174 commented on apps/form-builder/src/components/FormSubmissions/TextQuestionAnalytics.tsx
> +        (element) => element.question._id.toString() === question._id.toString()
Check if the num is equal to -1, which means that there was no response to that question. If equal to -1, just don't add to the array and go to the next iteration of the for loop.

2024-04-09 03:52 UTC, LSmith2174 commented on apps/form-builder/src/components/FormSubmissions/TextQuestionAnalytics.tsx
> +    <Sheet
Get rid of this sheet component so that the person using the text questions analytics component can instead choose the size when using it.

2024-04-09 03:52 UTC, LSmith2174 commented on apps/form-builder/src/components/FormSubmissions/TextQuestionAnalytics.tsx
> +  function getSubmission() {
This function is getting multiple answers, so I suggest renaming to `getAnswers()`.

2024-04-22 03:05 UTC, andlrutt approved these changes

2024-04-23 17:37 UTC, merged